source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.1"

gem "rails", "~> 7.0.4", ">= 7.0.4.3"
gem 'active_model_serializers', '~> 0.10.0'
gem 'pg', '~> 1.1'
gem 'i18n'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rack-cors'
gem 'devise'
gem 'devise_token_auth'

group :development, :test do
  gem 'rspec-rails', '~> 4.0'
  gem 'database_cleaner'
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'shoulda-matchers', require: false
  gem 'factory_bot_rails'
  gem 'pry-rails'
  gem 'pry'
  gem 'faker'
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'rubocop-rails'
end

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]