default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: cnab_api_development

test:
  <<: *default
  database: cnab_api_test

production:
  <<: *default
  database: cnab_api_production
